### ISSUE TITLE
May I inquire about the release plan for the waypoint model training and evaluation code?

### ISSUE THREAD

**Issue by statjuns** [MarSaKi/ETPNav#1]
Thank you for sharing your code.

May I inquire about the release plan for the waypoint model training and evaluation code? If the code is not available for sharing, could you kindly provide me with the specifics of the waypoint prediction metric? For example, which distance metric is utilized for Chafer and Hausdorff distance? Thank you.

**Comment by MarSaKi** [comment]
Hi, 
Thanks for your interest. 
My colleague [Zun Wang](https://github.com/wz0919) will open-source waypoint training code recently. 
Thanks for your patience!
