### ISSUE TITLE
When will pre-training code be released?

### ISSUE THREAD

**Issue by Routine113** [MarSaKi/ETPNav#4]
Dear author, when will the pre-training code be released？
Looking forward to your reply, thank you for taking the time to resolve my request.

**Comment by MarSaKi** [comment]
Thanks for your attention！
You can run this [repo ](https://github.com/MarSaKi/VLN-BEVBert/tree/main/bevbert_ce/pretrain) to get the pre-trained model, note that you should comment the local branch of bevbert.

**Comment by MarSaKi** [comment]
The pretraining code is now available.

**Comment by Routine113** [comment]
> The pretraining code is now available.

oh，thank you very much！
